### PR TITLE
Fix package compatibility with librdkafka 1.2.1

### PR DESCRIPTION
**Pull request by dchem**
Fix nimble package manager warnings

### CODE REVIEW

**Comment by dchem** [comment]
If we wanted to get fancy we could put something like this in `.nimble` file, but I don't think that's warranted, since you would have to either do `execShellCmd` or call some other proc to figure it out.
```
before install:
  <some_code_here_to_determine_librdkafka_ver>
```

**Comment by dfdeshom** [comment]
Hi, why not target 1.2.1, instead of the RC release?

**Comment by dchem** [comment]
Ok, I can target it for 1.2.1

**Comment by dchem** [comment]
@dfdeshom it turns out that I was targetting 1.2.1 (same commit hash as https://github.com/edenhill/librdkafka/commit/e72fde03da75041cae47084148fc0f8a89a1abd4)

I rebuilt it and it works with 1.2.1 and not just with 1.2.1-RC1

**Comment by dfdeshom** [comment]
thanks!

**Pull request merged**
